language: php

sudo: false

php:
  - 7.1
  - 7.2
  - 7.3

matrix:
  include:
    - php: 5.6
      env: NETTE_VERSION='2.2.*'
    - php: 5.6
      env: NETTE_VERSION='2.4.*'
    - php: 7.0
      env: NETTE_VERSION='2.4.*'

before_script:
  - travis_retry composer install --prefer-source

script:
  - phpunit
